<?php
header('Content-Type: text/xml;charset=UTF-8');
include("conn_clean.php"); 
set_time_limit(6000);
ini_set("memory_limit","24M");
  $pnow=getdate();
  $ppnow=$pnow['year'] . "-" . $pnow['mon'] . "-" .$pnow['mday'];
    $sqlstr="SELECT species.*, main.*, station.*, project.* FROM ((main INNER JOIN project ON main.Project_id = project.Project_id) INNER JOIN species ON main.scientific_name = species.scientific_name) INNER JOIN station ON main.id = station.id where record_id=". $_GET['record_id'];
    $result=mysql_query($sqlstr,$link_ID);
     $arr[$index]=mysql_fetch_array($result); 
	 echo "<?xml version='1.0' encoding='utf-8'?>";
	 
	 echo "<SimpleDarwinRecordSet";
     echo " xmlns='http://rs.tdwg.org/dwc/xsd/simpledarwincore/'";
      echo " xmlns:dc='http://purl.org/dc/terms/'";
       echo " xmlns:dwc='http://rs.tdwg.org/dwc/terms/'";
       echo " xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'";
       echo " xsi:schemaLocation='http://rs.tdwg.org/dwc/xsd/simpledarwincore/ http://rs.tdwg.org/dwc/xsd/tdwg_dwc_simple.xsd'>";
       echo "<SimpleDarwinRecord>";
echo "<dc:modified>".$ppnow."</dc:modified>";
echo "<dwc:occurrenceID>urn:lsid:wlterm.biodiv.sinica.edu.tw:observation:" . $arr[$index]['record_id']."</dwc:occurrenceID>";
echo "<dwc:catalogNumber>".$arr[$index]['record_id']."</dwc:catalogNumber>";
         echo "<dwc:scientificName>".$arr[$index]['scientific_name'] . "</dwc:scientificName>";
         echo "<dwc:basisOfRecord>O</dwc:basisOfRecord>";
         echo "<dwc:kingdom>". $arr[$index]['kingdom'] . "</dwc:kingdom>";
         echo "<dwc:phylum>".$arr[$index]['phylum'] . "</dwc:phylum>";
         echo "<dwc:class>".$arr[$index]['class'] . "</dwc:class>";
         echo "<dwc:order>".$arr[$index]['order'] ."</dwc:order>";
         echo "<dwc:family>".$arr[$index]['family'] . "</dwc:family>";
         echo "<kingdomInChinese>".$arr[$index]['kingdom_c'] ."</kingdomInChinese>";
         echo "<phylumInChinese>".$arr[$index]['phylum_c'] ."</phylumInChinese>";
         echo "<classInChinese>".$arr[$index]['class_c'] ."</classInChinese>";
         echo "<orderInChinese>".$arr[$index]['order_c'] ."</orderInChinese>";
         echo "<familyInChinese>".$arr[$index]['family_c'] ."</familyInChinese>";
         echo "<chineseName>".htmlspecialchars($arr[$index]['chinese']) ."</chineseName>";
         echo "<dwc:scientificName>".htmlspecialchars($arr[$index]['scientific_name']) . "</dwc:scientificName>";
         echo "<dwc:scientificNameAuthorship>".htmlspecialchars($arr[$index]['author']) . "</dwc:scientificNameAuthorship>";
         echo "<dwc:identifiedBy>".htmlspecialchars($arr[$index]['identified_by']) ."</dwc:identifiedBy>";
         echo "<dwc:recordedBy>".htmlspecialchars($arr[$index]['collector']) ."</dwc:recordedBy>";
         echo "<recordedByInChinese>".htmlspecialchars($arr[$index]['collector_chinese']) ."</recordedByInChinese>";
          echo "<dwc:eventDate>".$arr[$index]['date']."</dwc:eventDate>";
          echo "<eventDateEnd>".$arr[$index]['date_end']."</eventDateEnd>";
         echo "<dwc:locality>".htmlspecialchars($arr[$index]['locality']) ."</dwc:locality>";
         echo "<localityInChinese>".htmlspecialchars($arr[$index]['locality_chinese']) ."</localityInChinese>";
         echo "<dwc:decimalLongitude>".$arr[$index]['longitude'] ."</dwc:decimalLongitude>";
         echo "<dwc:decimalLatitude>".$arr[$index]['latitude'] ."</dwc:decimalLatitude>";
         echo "<dwc:coordinateUncertaintyInMeters>".$arr[$index]['coordinate_precision'] ."</dwc:coordinateUncertaintyInMeters>";
         echo "<dwc:minimumElevationInMeters>".$arr[$index]['minimum_elevation'] ."</dwc:minimumElevationInMeters>";
         echo "<dwc:maximumElevationInMeters>".$arr[$index]['maximum_elevation'] ."</dwc:maximumElevationInMeters>";
         echo "<dwc:minimumDepthInMeters>".$arr[$index]['minimum_depth'] ."</dwc:minimumDepthInMeters>";
         echo "<dwc:maximumDepthInMeters>".$arr[$index]['maximum_depth'] ."</dwc:maximumDepthInMeters>";
         echo "<dwc:individualCount>".$arr[$index]['individual_count'] ."</dwc:individualCount>";
         echo "<dwc:occurrenceDetails>全天光空域:" .  $arr[$index]['全天光空域'] . ", 直射光空域:" . $arr[$index]['直射光空域'] . ", 測站描述:" . $arr[$index]['Locality_Describe']."</dwc:occurrenceDetails>";
         echo "<projectName>".$arr[$index]['projectname'] ."</projectName>";
         echo "<executivePeriod>".$arr[$index]['executiveperiod'] ."</executivePeriod>";
         echo "<associatedAgency>".htmlspecialchars($arr[$index]['associatedagency']) ."</associatedAgency>";
         echo "<executiveAgency>".htmlspecialchars($arr[$index]['executiveagency']) ."</executiveAgency>";
         echo "<hostName>".htmlspecialchars($arr[$index]['hostname']) ."</hostName>";
         echo "<hostNameInChinese>".htmlspecialchars($arr[$index]['hostname_chinese']) ."</hostNameInChinese>";
         echo "<hostAddress>".htmlspecialchars($arr[$index]['hostaddress']) ."</hostAddress>";
         echo "<e-Mail>".htmlspecialchars($arr[$index]['hoste_mail']) ."</e-Mail>";
         echo "<coordination>".htmlspecialchars($arr[$index]['coordination']) ."</coordination>";
         echo "<executiveWay>".htmlspecialchars($arr[$index]['executiveway']) ."</executiveWay>";
         echo "<projectSummary>".htmlspecialchars($arr[$index]['projectsummary']) ."</projectSummary>";
   echo "</SimpleDarwinRecord>"; 
   echo "</SimpleDarwinRecordSet>"; 
?>